name: Logical CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Esy
      run: npm install -g esy
    - name: Install dependencies
      run: esy install
    - name: Build the project
      run: esy build
    - name: Run tests
      run: esy test
